"""
semantic_enricher.py  (OpenAI Edition)
---------------------------------------
Standalone enrichment script that post-processes the hierarchical JSON dataset
generated by agent.py. For every code diff chunk it calls the OpenAI ChatCompletion
API to generate a natural-language explanation (`diff_explain`) and saves the
enriched result next to the original file as [filename]_enriched.json.

Usage:
    .\\venv\\Scripts\\python.exe semantic_enricher.py [optional: path/to/dataset.json]

Requires a .env file in the project root with:
    OPENAI_API_KEY=sk-...
"""

import os
import sys
import json
import glob
import logging
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv
from openai import OpenAI
from tqdm import tqdm

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
log_dir = "log"
os.makedirs(log_dir, exist_ok=True)
run_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
log_file = os.path.join(log_dir, f"enricher_run_{run_timestamp}.log")

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(log_file),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Security: ensure .env is in .gitignore
# ---------------------------------------------------------------------------
def ensure_env_in_gitignore():
    gitignore_path = Path(".gitignore")
    entry = ".env"
    if gitignore_path.exists():
        content = gitignore_path.read_text(encoding="utf-8")
        # Check line-by-line to avoid substring false-positives
        lines = [l.strip() for l in content.splitlines()]
        if entry not in lines:
            with gitignore_path.open("a", encoding="utf-8") as f:
                f.write(f"\n# OpenAI credentials — auto-added by semantic_enricher.py\n{entry}\n")
            logger.info(".env appended to .gitignore to prevent credential leakage.")
        else:
            logger.info(".env is already listed in .gitignore.")
    else:
        logger.warning(".gitignore not found — skipping auto-protection. Create one and add .env manually.")

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
MODEL = "gpt-4o-mini"
MAX_TOKENS = 512

SYSTEM_PROMPT = (
    "You are an AI Data Engineer expert in creating Instruction-Tuning datasets (Alpaca/Instruct format). "
    "Your task is to generate a single, direct imperative instruction that a developer would write as a prompt to request the SPECIFIC code modification shown in the diff. "
    "CRITICAL RULES TO AVOID OVERFITTING AND DICTATION: "
    "1. The instruction MUST identify the specific method/class changed by reading its signature EXACTLY as it appears in the [CODE DIFF]. NEVER extract the method/property name from the Commit description. "
    "2. When identifying the component, mention the class or file name NATURALLY, as a human developer would in a chat. DO NOT use full file paths. (e.g., BAD: 'Update Dispose in folder/path/Control.cs'. GOOD: 'Update the Dispose method in the Control class'). "
    "3. DO NOT simply copy or repeat the Commit description. Use the Commit context ONLY to understand the business intent. "
    "4. NEVER include literal code snippets, operators (e.g., '==', '>='), or exact syntax in your instruction. Explain the goal conceptually so the future AI learns to write the code itself. "
    "5. Start immediately with an imperative action verb (e.g., Update, Fix, Add, Refactor, Remove, Implement). "
    "6. Do NOT use conversational or passive language. "
    "7. Keep it strictly to 1 or 2 concise sentences maximum."
)

USER_PROMPT_TEMPLATE = """\
Analyze the provided Commit context, the file name, and the raw code modifications. 
Synthesize the ideal user prompt/instruction that would command THIS EXACT software change.

CRITICAL CONSTRAINTS:
- Identify the exact Method or Property name from the [CODE DIFF] signature. 
- Use the provided `file_name` to deduce the name of the class or component being modified. Incorporate this name NATURALLY into the instruction to avoid ambiguity (e.g., "in the Bitmap class"). Do NOT output the raw file path.
- Bridge the gap between Business Intent and Technical Implementation. Analyze the [CODE DIFF] to understand WHAT changed, but use the [COMMIT CONTEXT] to understand WHY.
- Frame the instruction as a logical problem to solve, NOT as a dictation of keystrokes.
- If `raw_old_code` is empty or missing, formulate it as a creation request: "Add the [ExactNameFromDiff] method/property to the [ClassName] class to handle [Business Logic]".
- Output ONLY the imperative instruction.

[COMMIT CONTEXT]
commit_description: {commit_description}

[FILE INFO]
file_name: {file_name}

[CODE DIFF]
raw_old_code: 
{raw_old_code}

raw_new_code: 
{raw_new_code}
"""

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def find_latest_dataset() -> str:
    """Return the most-recently modified agent_run_*.json in ./output/."""
    files = sorted(
        glob.glob("./output/agent_run_*.json"),
        key=os.path.getmtime,
        reverse=True,
    )
    if not files:
        raise FileNotFoundError("No agent_run_*.json found in ./output/")
    return files[0]


def format_list(items) -> str:
    """Convert a comments list to a readable inline string."""
    if not items:
        return "(none)"
    return " | ".join(str(i).strip() for i in items if str(i).strip())


def count_diffs(data: list) -> int:
    total = 0
    for item in data:
        commit = item.get("commit", {})
        for file_ in commit.get("files", []):
            total += len(file_.get("file_diffs", []))
    return total


# ---------------------------------------------------------------------------
# OpenAI call
# ---------------------------------------------------------------------------
def generate_explanation(
    client: OpenAI,
    commit_description: str,
    file_name: str,
    diff: dict,
) -> str:
    raw_old = diff.get("raw_old_code", "") or ""
    raw_new = diff.get("raw_new_code", "") or ""

    user_msg = USER_PROMPT_TEMPLATE.format(
        commit_description=commit_description,
        file_name=file_name,
        raw_old_code=raw_old,
        raw_new_code=raw_new,
    )

    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": user_msg},
        ],
        max_tokens=MAX_TOKENS,
        temperature=0.2,  # near-deterministic for dataset consistency
    )

    return response.choices[0].message.content.strip()

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    # ---- security setup ----
    ensure_env_in_gitignore()

    # ---- load secrets ----
    load_dotenv()
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        logger.error(
            "OPENAI_API_KEY not found. Create a .env file in the project root "
            "with OPENAI_API_KEY=sk-... and re-run."
        )
        sys.exit(1)

    client = OpenAI(api_key=api_key)

    # ---- resolve input file ----
    if len(sys.argv) > 1:
        input_path = sys.argv[1]
    else:
        input_path = find_latest_dataset()

    logger.info(f"Input dataset : {input_path}")

    with open(input_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # ---- resolve output path ----
    input_stem  = Path(input_path).stem          # e.g. agent_run_20260421_160938
    output_dir  = Path(input_path).parent        # ./output
    output_path = output_dir / f"{input_stem}_enriched.json"
    logger.info(f"Output path   : {output_path}")

    # ---- count diffs for progress bar ----
    total_diffs = count_diffs(data)
    logger.info(f"Total diff chunks to enrich: {total_diffs}")

    # ---- iterate hierarchy ----
    errors = 0
    with tqdm(total=total_diffs, desc="Enriching diffs", unit="diff") as pbar:
        for item in data:
            commit = item.get("commit", {})
            commit_description = commit.get("commit_description", "")

            for file_ in commit.get("files", []):
                file_name = file_.get("file_name", "")

                for diff in file_.get("file_diffs", []):
                    try:
                        explanation = generate_explanation(
                            client,
                            commit_description,
                            file_name,
                            diff,
                        )
                        diff["diff_explain"] = explanation
                    except Exception as e:
                        errors += 1
                        logger.error(f"Error on diff in {file_name}: {e}")
                        diff["diff_explain"] = ""
                    finally:
                        pbar.update(1)

    logger.info(f"Enrichment complete. Errors: {errors}/{total_diffs}")

    # ---- save enriched dataset ----
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    logger.info(f"Enriched dataset saved to: {output_path}")


if __name__ == "__main__":
    main()